### ISSUE TITLE
[My DB server Hacked]

### ISSUE THREAD

**Issue by lastdarken** [FusionGen/FusionGen#10]
database; auth/characters all tables update to FUCKYOU !

![photo_2020-05-11_13-23-00](https://user-images.githubusercontent.com/63067250/81542933-a880ba80-938a-11ea-8f17-6bfb7b1e1657.jpg)

The connection was from the site by user account.
Access user:
update/select/insert

**Comment by omghixd** [comment]
I have **_a lot_** of questions.

1.) What were you hosting on?: 
2.) Were your DB Users securely created? (give an example of how one account would look like):
3.) PHP Version?:
4.) When did you last update the CMS?:
5.) Was this done to **all databases** or just that one?
6.) Was this done on the CMS **Database** or the Server **Database**?:

- More follow-up questions may be asked. But please answer these as good as you can! :)

**Comment by lastdarken** [comment]
1. ovh Direct Admin.
2. yes.
3. Phpversion 7.
4. version cms: https://github.com/FusionGen/FusionGen/commit/69820fc2be7ff793bd8f06d70d4bd6db16a90037
5. all tables update to FUCKYOU! auth and characters.

i creat a user/acc in mysql database vps and give to cms for connections.
i have linux vps and just enable port 3306 for host + deny for all port 3306.

Access user:
update/select/insert

**Comment by omghixd** [comment]
> I have **_a lot_** of questions.
> 
> 1.) What were you hosting on?:
> 2.) Were your DB Users securely created? (give an example of how one account would look like):
> 3.) PHP Version?:
> 4.) When did you last update the CMS?:
> 5.) Was this done to **all databases** or just that one?
> 6.) Was this done on the CMS **Database** or the Server **Database**?:
> 
> * More follow-up questions may be asked. But please answer these as good as you can! :)

Please fill out the format properly. I'm missing a lot of information.

**Comment by lastdarken** [comment]
1. ovh Direct Admin.
2. yes.
3. Phpversion 7.
4. version cms: 69820fc
5. all tables update to FUCKYOU! auth and characters.
6. cms database in to host.

I didn't see any changes in host file or database, just db server hack!

**Comment by omghixd** [comment]
> 1. ovh Direct Admin.
> 2. yes.
> 3. Phpversion 7.
> 4. version cms: [69820fc](https://github.com/FusionGen/FusionGen/commit/69820fc2be7ff793bd8f06d70d4bd6db16a90037)
> 5. all tables update to FUCKYOU! auth and characters.
> 6. cms database in to host.
> 
> I didn't see any changes in host file or database, just db server hack!

Answer number 2 is incorrect. Can you make an Example user of how the Username and password would look like? We are still missing a lot of information.

**Comment by lastdarken** [comment]
2.  
user: webs!te 
pass: ygin@c0#%&!

**Comment by omghixd** [comment]
Not saying this is your fault at all. i'm just saying we require this informamtion to determine wether it was a problem on your end or the CMS End.

What permission (example: 755) does your config have?

**Comment by alexandre433** [comment]
How is phpmyadmin enabled?
Can anyone access it if they go for - http://<yourdomain.com>/phpmyadmin?

**Comment by lastdarken** [comment]
@alexandre433 
host is for ovh, secure!
I send ticket to support hosting, He told me there was a problem with your site's scripts, not for hosting.

I removed cms and added A page register.
There was no problem anymore.

**Comment by omghixd** [comment]
Did they happen to tell you where they located the problem in "your" site?

**Comment by lastdarken** [comment]
They just said your site is not secure.

please use wordpress, joomla or system sites original.

**Comment by omghixd** [comment]
Then we are back to zero then.

**Comment by lastdarken** [comment]
I think buger can see informations  user/pass mysql connects!

but how?

**Comment by omghixd** [comment]
> I think buger can see informations user/pass mysql connects!
> db or php
> 
> but how?

This is what we are trying to figure out. And this is why we ask a lot of questions. Its blind-like debugging. We have a few pinpointers on what it could be but are yet to be one 100% sure where and why this happens.

**Comment by lastdarken** [comment]
This is my biggest doubt:

Table realms

user/pass mysql;
ip/ports;
acc/pass; admin console.

**Comment by omghixd** [comment]
We appreciate the information given unfortunately this isn't gonna tell us exactly where the problem persists.

**Comment by lastdarken** [comment]
What permission (example: 755) does your config have?

![Untitled](https://user-images.githubusercontent.com/63067250/81499182-d0b2df80-92de-11ea-8597-f97d665a7772.png)

**Comment by lastdarken** [comment]
I think buger can't visit *php cfg files

Just can see table realms.

All information connects is to this table!

**Comment by omghixd** [comment]
No they cant read php or cfg files context. That was sanitized by the developers of php ages ago, not even sure if it ever was possible.

**Comment by lastdarken** [comment]
For test:
if you can delete table realms and add connects to a cfg file by permissions 0644?

**Comment by lastdarken** [comment]
@omghixd

Is it difficult to do this?

**Comment by lineagedr** [comment]
@lastdarken Yes. Test it again and let us know how it goes.

**Comment by lastdarken** [comment]
ok, dear
I again installed
but i fear :smile:

**Comment by alexandre433** [comment]
Should have been fixed on #12 

If the problem presists, please open another issue.
