### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by yuanf225** [FusionGen/FusionGEN#100]
MySQL Version:5.6.28
PHP Version: 7.1.33
Nginx：1.20.1
Latest FGEN Version (Yes/No): Yes
Which branch (Master / SRP6): SRP6

I am not sure if it is because of Nginx, only the home page is displayed properly after installation, clicking any link will be a 404 error

This is my Nginx configuration file
`server
{
    listen 80;
    server_name www.tbcstar.com;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/www.tbcstar.com/;
    
    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #SSL-END
    
    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    #error_page 404 /404.html;
    #error_page 502 /502.html;
    #ERROR-PAGE-END
    
    #PHP-INFO-START  PHP引用配置，可以注释或修改
    include enable-php-71.conf;
    #PHP-INFO-END
    
    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/www.tbcstar.com.conf;
    #REWRITE-END
    
    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }
    
    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }
    
    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        error_log /dev/null;
        access_log /dev/null;
    }
    
    location ~ .*\.(js|css)?$
    {
        expires      12h;
        error_log /dev/null;
        access_log /dev/null; 
    }
    access_log  /www/wwwlogs/www.tbcstar.com.log;
    error_log  /www/wwwlogs/www.tbcstar.com.error.log;
}`

**Comment by yuanf225** [comment]
Whether to replace the contents related to location as described in the wiki

**Comment by yuanf225** [comment]
include /www/server/panel/vhost/rewrite/www.tbcstar.com.conf; I see the content is empty. Do I need to add anything ?

**Comment by yuanf225** [comment]
In include/www/server/panel/vhost/rewrite/www.tbcstar.com.conf file 
added:`<Directory /www/wwwroot/www.tbcstar.com/>
AllowOverride All
Require all granted
</Directory>`
Right?

**Comment by Err0r1** [comment]
Mate, google it
Rewrite rules != htaccess/AllowOverride All option ;-)

**Comment by OMGhixD-OG** [comment]
> problem not confirm Debian 11 php 7.4 mariaDB 10.x nginx web server

Also 

php 7.4
mariaDB 10.x

You can only use
PHP 7.1.33 (Required)
MySQL Server 5.7 (Required) // I.E an equal version in MariaDB.

would also be nice if you made your own issue report

**Comment by OMGhixD-OG** [comment]
//Closed
