### ISSUE TITLE
Final Setup Page:  Stuck on "Please Wait..."

### ISSUE THREAD

**Issue by angrytoilet** [FusionGen/FusionGEN#113]
What are you specifically reporting:
When entering in the master account, it sticks on "please wait..."

How do we replicate this issue that you are encountering?:
I am using a custom SQL port.  Original issue was on "do_realms.php" and "do_database.php".  Resolved by Err0r but persists to finalize.

Are you hosting FusionGen on a All-in-One Package or an Webhost:
Using FusionGEN and via Xampp from a NAS/VM

Have you made any personal modifications? If so, What?:
No modifications

PHP Version:
Using the required 7.1.33

**Comment by Err0r1** [comment]
Seems all the issues are fixed with the PRs (still awaiting merge)
