### ISSUE TITLE
Password Recovery for SRP6 and SPH selection ideology is missing

### ISSUE THREAD

**Issue by OMGhixD-OG** [FusionGen/FusionGEN#115]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
- Currently, we have Password_Recovery module for SRP6 and SPH, but there is no functionality behind this to select either or. Meaning that you have to pretty much have to hardcode link users to the specific password_recovery module that you are to use. And that isn't exactly convenient?

**Describe the solution you'd like**
- This should be an automated process and should be established throughout the installation, if SRP6 is selected then we should link to that. If the other way then, the other way the ideology goes.

**Describe alternatives you've considered**
- I've considered to have this in the installer, That will require some past knowledge of the core and its password encryption method (which not everyone might have, thus it may not be the best approach)
- Link it with the already checking system for the new emulator files. These files already determine whether it is SRP6 or SPH
- Open for suggestions

**Additional context**
- None

**Comment by Err0r1** [comment]
https://github.com/FusionGen/FusionGEN/issues/116
