### ISSUE TITLE
Installer: can't found auth database

### ISSUE THREAD

**Issue by peypi0** [FusionGen/FusionGEN#119]
Hi
When hostname is different with the auth_hostname, at installer can't found auth database and this error occurred:
`Looks like your auth database doesn't exist`

**Comment by Err0r1** [comment]
Your auth database must also exist on the auth_hostname and the user must have access to it

**Comment by peypi0** [comment]
@Err0r1 
Please check pr.
Do not need that line. Of course, there is a mistake host for mysqli_auth connection.

**Comment by Err0r1** [comment]
Yes, i see, a typo
Then please fix it in the right way and not remove the whole check

**Comment by peypi0** [comment]
@Err0r1 
You already defined `$mysqli_auth` at line 20.
Why you want to define it twice?
