### ISSUE TITLE
A Database Error Occurred

### ISSUE THREAD

**Issue by mpfans** [FusionGen/FusionGEN#123]
my server use azerothcore,  use the account activation system,fill in the registration information and click Submit, report an error

![image](https://user-images.githubusercontent.com/18187177/155053526-908a2a67-bd27-4ece-9d79-feb3d4a39f6e.png)

**Comment by mpfans** [comment]
if `$config['enable_email_activation'] = false;`  The account can be created successfully

**Comment by Err0r1** [comment]
https://github.com/FusionGen/FusionGEN/issues/122
