### ISSUE TITLE
Password Recovery

### ISSUE THREAD

**Issue by Tony931023** [FusionGen/FusionGEN#128]
When I give FusionGen to recover my password I get a 403 error

**Comment by Err0r1** [comment]
Where do you get a 403 error?
What kind of 403 error?
Is there a log?

**Comment by mpfans** [comment]
> Where do you get a 403 error? What kind of 403 error? Is there a log?

![image](https://user-images.githubusercontent.com/18187177/165908756-0ee521ac-b6ef-4197-a397-7a9563bc54e4.png)

**Comment by mpfans** [comment]
All fusingen have this error

**Comment by Err0r1** [comment]
Thats the default error page, if url doesn't exist (like forums)

For PW recovery, you have to enable SMTP and setup mailserver connection

In the update there will be a debug tool for easier mailserver connection

**Comment by mpfans** [comment]
> Thats the default error page, if url doesn't exist (like forums)
> 
> For PW recovery, you have to enable SMTP and setup mailserver connection
> 
> In the update there will be a debug tool for easier mailserver connection

click 'password_recovery' Then the above error appears

**Comment by Err0r1** [comment]
Ah, got it

Yes, thats cause of split "SHP/SRP6". Never finished.
So PW recovery is atm broken

**Comment by mpfans** [comment]
> Ah, got it
> 
> Yes, thats cause of split "SHP/SRP6". Never finished. So PW recovery is atm broken

yes.. this is the same as sending an error when registering an account, so I will consult you about your progress a few days ago
https://github.com/FusionGen/FusionGEN/issues/115

**Comment by Err0r1** [comment]
Yes, this will all be fixed in the update

**Comment by mpfans** [comment]
tyvm,I've been waiting

**Comment by mpfans** [comment]
> Yes, this will all be fixed in the update

I suggest fix PW recovery  and registering the email verification first, and others can be postponed
