### ISSUE TITLE
Store error

### ISSUE THREAD

**Issue by Slipy007** [FusionGen/FusionGEN#130]
Hi,

I might not have a module or maybe it's not working correctly. But how do I fix this issue when hovering over a store item?

https://imgur.com/a/wgCRnSA

Thank you for taking the time to read this and help me.

**Comment by Err0r1** [comment]
Webserver issue
Increase php memory size, check if tooltip module is enabled.

**Comment by Slipy007** [comment]
> Webserver issue Increase php memory size, check if tooltip module is enabled.

Increasing the memory size in php worked. Thank you for your help.
