### ISSUE TITLE
Armory 3.3.5

### ISSUE THREAD

**Issue by Jwh1o1** [FusionGen/FusionGEN#131]
I am having an issue with the armory.
When I go to view characters I get some .php errors.
A PHP Error was encountered
Severity: Notice
Message: Trying to access array offset on value of type bool
Filename: templates/ce9f28db0579fd63e57e2fe95a0d5f3723cf91c5.file.character.tpl.php
Line Number: 47
 
A PHP Error was encountered
Severity: Notice
Message: Trying to access array offset on value of type bool
Filename: controllers/character.php
Line Number: 192

A PHP Error was encountered
Severity: Notice
Message: Trying to access array offset on value of type bool
Filename: controllers/character.php
Line Number: 197

I have installed the website to my apache server with php version 7.4.26
I have not modified anything. 
My wow server is a 3.3.5 Trinity core. 

I think that it is trying to pull a value that my database might not have but I am not sure what or how to fix it. I did check my database and the characters database has Power1-7 but not MaxPower1-6.  The items load fine as well but the middle looks odd.
![error](https://user-images.githubusercontent.com/4356068/181877252-4b298232-128b-4f4a-a776-8d2e79b8bf92.png)

**Comment by Err0r1** [comment]
PHP7.4 is not supported
Read the requirements
