### ISSUE TITLE
Armory showing No stats or gems

### ISSUE THREAD

**Issue by Jwh1o1** [FusionGen/FusionGEN#132]
Thank you for all the hard work put into this it looks really good and so far I have been able to get a lot of it working. I am noticing the armory having an issue pulling certain pieces of information like player stats. It pulls player information and items in slots correctly. It does not have item gems but I am not sure if that is a feature or not.

Armory only pulling some of the information.

I go into the armory search for a player on my server and click to view.

I have FusionGen installed on my apache server. 

I have a Trinity Core server 3.3.5a and its connected with rbac_soap

I have not made any modifications.

Php version 7.1.33
![error](https://user-images.githubusercontent.com/4356068/182002732-d5342d37-1a1e-452a-9831-03baeb3fd243.png)

**Comment by Err0r1** [comment]
You have to enable stats in your worldserver config.

Gems/enchants are not supported

**Comment by Jwh1o1** [comment]
#    PlayerSave.Stats.MinLevel
#        Description: Minimum level for saving character stats in the database for external usage.
#        Default:     0  - (Disabled, Do not save character stats)
#                     1+ - (Enabled, Level beyond which character stats are saved)

PlayerSave.Stats.MinLevel = 1

#
#    PlayerSave.Stats.SaveOnlyOnLogout
#        Description: Save player stats only on logout.
#        Default:     1 - (Enabled, Only save on logout)
#                     0 - (Disabled, Save on every player save)

PlayerSave.Stats.SaveOnlyOnLogout = 0

^this is how it is in my .conf file is there a spot I can check in my database to verify its working?

**Comment by Err0r1** [comment]
Reload config and relog char

**Comment by Jwh1o1** [comment]
Thank you for the fast responses! I had to remake the character_stats table it was not updating for some reason. I dropped the table and rebuilt it and it now saves the stats from the players.
