### ISSUE TITLE
BUG Page Admin

### ISSUE THREAD

**Issue by htc16** [FusionGen/FusionGEN#133]
I'm using php7.3, and then this error started to appear in the admin panel.
This error seems to be just visible, because when I give CTRL + F5 it allows me to perform the desired function. But it still shows errors elsewhere on the page.
I have no idea what it is, as it wasn't like this before, but I didn't mess with it.

![image](https://user-images.githubusercontent.com/58153179/189701649-2b17b397-642a-4170-8860-e4bedf68c41f.png)

AFTER GIVING CTRL + F5

![image](https://user-images.githubusercontent.com/58153179/189702129-21143eea-b7d5-4ce0-b2d6-df73f5e2ac5d.png)

**Comment by Err0r1** [comment]
Add a custom page and error should be "fixed" for now

**Comment by htc16** [comment]
> 

I didn't understand

**Comment by Err0r1** [comment]
Left menu -> custom page -> add a page

**Comment by htc16** [comment]
This actually happened after I deleted my custom pages and as I couldn't tell...lol

goooood

Thanks!!!
