### ISSUE TITLE
Error when buying in Store

### ISSUE THREAD

**Issue by Beater901** [FusionGen/FusionGEN#140]
CORE-AC2019
FusionGenV2
Apache2Server
SOAP Enabled

**The error happens when I try to buy an item on the site.**

For example, in this case I wanted to buy an item in the Store and I got this error

```
Something went wrong! An administrator has been noticed and will send your order as soon as possible.

Error:
Method 'ns1:executeCommand' not implemented: method name or namespace not recognized
```

Thanks in advance for all you do for the community.

**Comment by Err0r1** [comment]
Issue is cause of the emulator

I will create a AzerothCore emulato for sha_hash_pass after new year
