### ISSUE TITLE
Unable to create Shadowland account

### ISSUE THREAD

**Issue by DevGamX** [FusionGen/FusionGEN#143]
First of all I am using CMS on Windows 11 with Wampserver, Apache 2.4.51 MySQL 5.7.36 and PHP 8.2 0

I couldn't create an account via the CMS, i constantly had this error : 

 => Severity: error --> Exception: current(): Argument #1 ($array) must be of type array, null given E:\Wamp64\www\mysite\application\emulators\trinity_rbac_sl_soap.php 402

So suddenly by dint of looking, i replaced part of the code of trinity_rbac_sl_soap.php by that of trinity_rbac_soap.php (see photo) 
and the account creation worked well.

![image](https://user-images.githubusercontent.com/118358135/210421055-9af70a88-fa71-4ff4-9edd-af09a6652bab.png)

**Comment by Err0r1** [comment]
https://github.com/FusionGen/FusionGEN/commit/99fdf9efcfbe66b37243003dfba041fddcaf34cb
