### ISSUE TITLE
Armory/wowhead/country restrictions

### ISSUE THREAD

**Issue by kkkkkkkkkkkkk-ddd** [FusionGen/FusionGEN#145]
Hey. 
My server is in country where wowhead is banned. 
So pics of items in armory wont load properly. 
I'm nooby when it comes to networking but will try can I see it from other devices using VPN.
Not sure does user load from my ip & served on user pc because wowhead restricted that country from access GOSH...
Sure I can use VPN but that would create other problems....
Any suggestions?  :'(

**Comment by favorit5503** [comment]
Images for items are loaded from this site. Try if it works for you. https://wow.zamimg.com/images/wow/icons/large/inv_chest_chain_16.jpg 
We are working on a solution to use DB for the data needed to run the armory.

**Comment by kkkkkkkkkkkkk-ddd** [comment]
No it doesn't  (sad face)
"We've discontinued servicing users from your location and are thereby preventing access to any of the websites owned and operated by ZAM Network, LLC DBA Fanbyte (the owner of Wowhead.com):"

**Comment by CraftedRO** [comment]
https://github.com/FusionGen/FusionGEN/commit/190189380729c9b166e460e61c5d62c7796f99d4
