### ISSUE TITLE
You can't even login in the new overhauled fusiongen

### ISSUE THREAD

**Issue by CraftedRO** [FusionGen/FusionGEN#149]
After few more tries you get ip banned on localhost kek :D

![sqsqsq](https://user-images.githubusercontent.com/24683355/212541831-b910f550-92ba-47d7-aca0-cc46f47c9800.PNG)

**Comment by Err0r1** [comment]
Can you post the error log in /application/logs/ pls?

**Comment by CraftedRO** [comment]
[log-2023-01-15.zip](https://github.com/FusionGen/FusionGEN/files/10420242/log-2023-01-15.zip)

**Comment by Err0r1** [comment]
Can you test after https://github.com/FusionGen/FusionGEN/commit/71b7f41122076a72543d7f9cd617feb5783cc717 pls?

**Comment by CraftedRO** [comment]
not sure why but it's same, and I still think I downloaded after commit
[log-2023-01-15.zip](https://github.com/FusionGen/FusionGEN/files/10420334/log-2023-01-15.zip)

**Comment by Err0r1** [comment]
PLs check in application/models/Internal_user_model.php on line 75 if its "id" or "uid"

**Comment by CraftedRO** [comment]
it seems even if  I redownloaded after commit
the typo application/models/Internal_user_model.php on line 75 if its "id" or "uid" was still there even if the table appeared :)

![failed](https://user-images.githubusercontent.com/24683355/212545072-a0314a35-2509-4a0b-94fa-efa0577c8b02.PNG)

not it works

**Comment by CyberMist2** [comment]
Confirm this issue is still persistent in [d280cf2](https://github.com/FusionGen/FusionGEN/commit/d280cf2cc56e4277b7dcd731593def6cb08cd262) emulator trinitycore wotlk https://github.com/TrinityCore/TrinityCore/pull/28793
