### ISSUE TITLE
Slow Armory

### ISSUE THREAD

**Issue by disclosurez** [FusionGen/FusionGen#15]
What are you specifically reporting (one report per issue):
Slow Armory
    How do we replicate this issue that you are encountering?`:
https://wotlkraids.com/armory - try use armory, very slow to search for characters, works fast after you click on a character.

- Ubuntu 20.04 LTS Webserver, MySQL 8, Php 7.2

**Comment by omghixd** [comment]
[https://cdn.discordapp.com/attachments/553651134409998352/709418328455905330/Screenshot_1.png](img)

Checking the performance tool in Microsoft edge DEV Build. These results came up.

Please fill out your report once more following this format.

https://github.com/FusionGen/FusionGen/issues/2

**Comment by disclosurez** [comment]
What are you specifically reporting (one report per issue):
- slow armory
    How do we replicate this issue that you are encountering?`:
- https://wotlkraids.com/armory
    Are you hosting FusionGen on a All-in-One Package or an Webhost:
- webhost ubuntu 20.04 lts
    Have you made any personal modifications? If so, What?:
- not to armory
    PHP Version:
-  MySQL 8, Php 7.2

**Comment by omghixd** [comment]
Regarding what i see, The first thing we should look at is downgrading PHP 7.2 to 7.1.33 (which is the required version explained by the README.MD file) I am aware some of the guides say 7.2 but that is wrong, **7.1.33** is the absolute recommended version.

**Comment by disclosurez** [comment]
Downgraded to 7.1.33 same issue

` php -v
PHP 7.1.33-15+ubuntu20.04.1+deb.sury.org+1 (cli) (built: Apr 28 2020 14:48:23) (                    NTS )
`

**Comment by omghixd** [comment]
That's weird. You wrote you hadn't done any personal modifications to the armory, but what about the rest of the cms? it is possible that **the** modification you made could impact the Armory searchs.

**Comment by disclosurez** [comment]
no other modifications, just crappy css

**Comment by disclosurez** [comment]
fixed it, 

/var/www/html/FusionGen/application/themes/default-wotlk/images/ajax.gif did not exist and causing the massive timeout @omghixd 

Uploading a newly created image fixed it.

https://wotlkraids.com/application/themes/default-wotlk/images/ajax.gif
