### ISSUE TITLE
Error on account registration

### ISSUE THREAD

**Issue by Steyfix** [FusionGen/FusionGEN#159]
Hello, I am running under a BFA core and with the "trinity_rbac_sl_soap" emulator, the accounts are created well and I have modified the extension insertion id in bdd. I specify that I can connect with the accounts created and I get the error on the screen below. Thanks.
![image](https://user-images.githubusercontent.com/12504219/214532260-a2f2542a-6d75-49f2-8e48-d19ac93bbcb6.png)

**Comment by favorit5503** [comment]
Hi, can you please post empty databases for auth, characters so i can make a new emulator for you.

**Comment by Steyfix** [comment]
hello I send you the link of the repository with in the sql file the auth table. I'm at work and I can't give you mine but it's the one I use cordially

https://github.com/AzgathCore/AzgathCoreBFA

**Comment by Err0r1** [comment]
Auth, characters and world.
But theres no need for a new emulator file

Salt is missing in rbac_sl_soap emulator
https://github.com/FusionGen/FusionGEN/commit/e7bc6101dbee68571c3673f71e6a3c8c2ccb6e53

**Comment by Err0r1** [comment]
Fixed
