### ISSUE TITLE
Donation log

### ISSUE THREAD

**Issue by Fullhouser** [FusionGen/FusionGEN#16]
Donations from paypal are not written into paypal_logs in database

OS: Windows Server 2016 Datacenter
Apache: 2.4.41
PHP: 7.1.33
DB: MySQL 8.0

**Comment by disclosurez** [comment]
Donations should be automated, and use API key - like blizzcms
https://gitlab.com/WoW-CMS/BlizzCMS-Plus/-/blob/master/application/modules/donate/controllers/Donate.php

**Comment by omghixd** [comment]
This broke over the years as PHP evolved. But yes, you are absolutely right. it should be automated, but it will require more checks as per today anyone can trick the FCMS Donation Module. I am yet to write a detailed report on this problem. So for now you'll have to manually accept donations and give points accordingly. Acting as a fail-safe method which unintentionally was added.

- To be continued.

**Comment by disclosurez** [comment]
$10 bounty added to whoever fixes this issue so that donations uses API keys instead, and works properly. Similar to BLizzCMS above
https://www.bountysource.com/issues/91399392-donation-log

**Comment by BarbzYHOOL** [comment]
> This broke over the years as PHP evolved. But yes, you are absolutely right. it should be automated, but it will require more checks as per today anyone can trick the FCMS Donation Module. I am yet to write a detailed report on this problem. So for now you'll have to manually accept donations and give points accordingly. Acting as a fail-safe method which unintentionally was added.
> 
>     * To be continued.

How is donation broken like that? never heard of that

**Comment by omghixd** [comment]
> > This broke over the years as PHP evolved. But yes, you are absolutely right. it should be automated, but it will require more checks as per today anyone can trick the FCMS Donation Module. I am yet to write a detailed report on this problem. So for now you'll have to manually accept donations and give points accordingly. Acting as a fail-safe method which unintentionally was added.
> > ```
> > * To be continued.
> > ```
> 
> How is donation broken like that? never heard of that

Php Updates, Core module didn't. 

- That is what i'm assuming.

**Comment by Err0r1** [comment]
https://github.com/FusionGen/FusionGEN/issues/116

Fixed soon

**Comment by Err0r1** [comment]
Fixed
