### ISSUE TITLE
Login issue still persistent

### ISSUE THREAD

**Issue by CyberMist2** [FusionGen/FusionGEN#164]
Confirming this issue is still persistent in [d280cf2](https://github.com/FusionGen/FusionGEN/commit/d280cf2cc56e4277b7dcd731593def6cb08cd262) emulator trinitycore wotlk https://github.com/TrinityCore/TrinityCore/commit/aeb4d18e20c444e828ecff0964013d3d8daf67d9

**Comment by CraftedRO** [comment]
why do you put my pull request as a core revision/hash, dude :) ?

**Comment by Err0r1** [comment]
Issue was fixed here
https://github.com/FusionGen/FusionGEN/commit/71b7f41122076a72543d7f9cd617feb5783cc717
and here
https://github.com/FusionGen/FusionGEN/commit/abb4621f0de0f2b283a0e060afcda3aa7d384b25

**Comment by CyberMist2** [comment]
> why do you put my pull request as a core revision/hash, dude :) ?

wrong link

**Comment by CyberMist2** [comment]
> Issue was fixed here [71b7f41](https://github.com/FusionGen/FusionGEN/commit/71b7f41122076a72543d7f9cd617feb5783cc717) and here [abb4621](https://github.com/FusionGen/FusionGEN/commit/abb4621f0de0f2b283a0e060afcda3aa7d384b25)

Used a fresh fusiongen installation, nothing happens when you click the login button on login page

**Comment by CraftedRO** [comment]
however I can't confirm on https://github.com/FusionGen/FusionGEN/commit/d280cf2cc56e4277b7dcd731593def6cb08cd262 and latest tc revision [aeb4d18e20c4](https://github.com/TrinityCore/TrinityCore/commit/aeb4d18e20c444e828ecff0964013d3d8daf67d9)

**Comment by CyberMist2** [comment]
the account is: admin pass is admin, probably the issue is because the account name in auth database is uppercase and password is less than 6 characters?

**Comment by CraftedRO** [comment]
that account is made with server command .account create right ?

**Comment by CraftedRO** [comment]
Yea indeed seems cms is set to allow login only on >= 6 length characters, maybe shoud we change that

**Comment by Err0r1** [comment]
Correct
Alrdy removed it

Will push it soon

PS: a password with <6 characters is not really secure

**Comment by CraftedRO** [comment]
indeed :)

**Comment by CyberMist2** [comment]
Atleast we found the issue guys, did the uppercase reason influenced it?

**Comment by CraftedRO** [comment]
no, uppercase doesn't influence it (from my tests) and it shoudn't

**Comment by Err0r1** [comment]
Login is now possible
Removed the character limit, so it sends the credentials to the login check
