### ISSUE TITLE
Max expansion

### ISSUE THREAD

**Issue by CraftedRO** [FusionGen/FusionGEN#166]
We got some problems with max expansions:
1. even if you set max expansion let's say wotlk (trinity_rbac_soap) at the installation, then in admin/settings you will see cataclysm as current max expansion selected (it shoud correspond with the installation choosed expansion instead).
2. max expansion at installation is Shadowlands (9.x.x) but still in acp you only have cata as a latest max expansion.
3. well last but not last recently added mangos emulators Zero, One, Two, Three are not listed yet.

**Comment by Err0r1** [comment]
Is disabled_expansion used at all?
Does something like that make sense?

Disabled_expansions is in the config but never used

**Comment by CraftedRO** [comment]
I think if I remember right back from when I had my server online, if you choose in your player account menu max expansion let's say tbc but the server is 3.3.5, you wasn't able to pass level 70 ingame (sound strange but this is how it was) and smth like this, didn't tested recently this thing.

**Comment by CraftedRO** [comment]
this is from a bit older cms version, now its seems the max expansion dropdown is empty

![max exp](https://user-images.githubusercontent.com/24683355/215737818-4b26e38a-b172-4f26-b203-b249d737f7f5.PNG)

**Comment by Err0r1** [comment]
Does this function even make sense?
Why should you limit yourself? If you don't want to play a DK or want to go to Northrend, you shouldn't just create one or fly there

disabled_expansions is useless btw. Checked the code

**Comment by CraftedRO** [comment]
It's up to you, the single reason I see for this is when a project is progressive and you don't need a patch for the server to disable things if this really works how it shoud.

**Comment by Err0r1** [comment]
Also in the master_old branch the function was useless

Well, I couldn't think of another reason either
They would have to deactivate things in the database/core anyway
e.g. they have a WotLk server, progress through vanilla and TBC, then ICC/ruby/etc would have to be disabled anyway

**Comment by CraftedRO** [comment]
you can't get to enter there if the entire map is disabled, I tested now if you take the boat it will teleport you at westfall gy for example and it does tell you you need wotlk expansion for that, also as I can see the specific xpansion rdf are also disabled but once again its up to you

**Comment by CraftedRO** [comment]
As a side note I will keep this feature alongside with many changes in my fork repository.

**Comment by Err0r1** [comment]
Yes, i get it
That simplifies a lot
If you then progress through the endcontent, you still have to do a lot

I will look what we can do

**Comment by CraftedRO** [comment]
y

**Comment by Err0r1** [comment]
Done in https://github.com/FusionGen/FusionGEN/commit/cbee061060151cfce16b35cc0c273641f5f84d9d
