### ISSUE TITLE
Account found ugly php errors

### ISSUE THREAD

**Issue by CraftedRO** [FusionGen/FusionGEN#167]
On trinitycore 3.3.5 srp6 emulator and latest cms version 1.0.7 are still present a lot of errors (they were since beginning) when you search for an account in admin pannel:

https://user-images.githubusercontent.com/24683355/216477688-2ef7da7f-1553-4c41-b8ff-4223a2a84c5b.mp4

```
A PHP Error was encountered
Severity: Warning

Message: Trying to access array offset on value of type bool

Filename: templates/f47b8f9dbc7968486082fc9cc843a81310f0dfb9_0.file.accounts_found.tpl.php

Line Number: 77

Backtrace:

File: D:\Games\Craftedwow\xampp\htdocs\application\cache\templates\f47b8f9dbc7968486082fc9cc843a81310f0dfb9_0.file.accounts_found.tpl.php
Line: 77
Function: _error_handler

File: D:\Games\Craftedwow\xampp\htdocs\application\third_party\Smarty\sysplugins\smarty_template_resource_base.php
Line: 123
Function: content_63dc4cc4d5c4f3_16359563

File: D:\Games\Craftedwow\xampp\htdocs\application\third_party\Smarty\sysplugins\smarty_template_compiled.php
Line: 114
Function: getRenderedTemplateCode

File: D:\Games\Craftedwow\xampp\htdocs\application\third_party\Smarty\sysplugins\smarty_internal_template.php
Line: 218
Function: render

File: D:\Games\Craftedwow\xampp\htdocs\application\third_party\Smarty\sysplugins\smarty_internal_templatebase.php
Line: 239
Function: render

File: D:\Games\Craftedwow\xampp\htdocs\application\third_party\Smarty\sysplugins\smarty_internal_templatebase.php
Line: 117
Function: _execute

File: D:\Games\Craftedwow\xampp\htdocs\application\libraries\Ci_smarty.php
Line: 78
Function: fetch

File: D:\Games\Craftedwow\xampp\htdocs\application\libraries\Template.php
Line: 467
Function: view

File: D:\Games\Craftedwow\xampp\htdocs\application\modules\admin\controllers\Accounts.php
Line: 125
Function: loadPage

File: D:\Games\Craftedwow\xampp\htdocs\index.php
Line: 250
Function: require_once


ERROR - 2023-02-02 23:59:10 --> Severity: Warning --> Undefined array key "gmlevel" D:\xampp\htdocs\application\cache\templates\f47b8f9dbc7968486082fc9cc843a81310f0dfb9_0.file.accounts_found.tpl.php 77
```

**Comment by Err0r1** [comment]
Which emulator file do u use?

**Comment by CraftedRO** [comment]
![sqsqsq](https://user-images.githubusercontent.com/24683355/216478475-82af5afd-31ef-42e2-9813-809307232289.PNG)

**Comment by Err0r1** [comment]
https://github.com/FusionGen/FusionGEN/commit/0eed2668a98f68399915281544e2c2487c0d108d

**Comment by CraftedRO** [comment]
as I coud tested now by replacing the files the problem stand still :(

> ERROR - 2023-02-03 01:41:30 --> Severity: Warning --> Trying to access array offset on value of type bool D:\Games\Craftedwow\xampp\htdocs\application\cache\templates\f47b8f9dbc7968486082fc9cc843a81310f0dfb9_0.file.accounts_found.tpl.php 77
and the others in admin panel too

**Comment by Err0r1** [comment]
Tested it with trinity auth DB..
did you replace all files?

**Comment by CraftedRO** [comment]
something is strange, on main (owner) account now works fine but when I choose the player account (same as in video) it still trow this error

**Comment by CraftedRO** [comment]
I think I had found the problem, if the account doesn't have any record in auth.account_access it will trow those erros

**Comment by Err0r1** [comment]
https://github.com/FusionGen/FusionGEN/commit/04d8adc2ad4d81d8c639a00c716b16675801bf33

Can you test pls? Should be fixed now

**Comment by CraftedRO** [comment]
ok the problem is fixed for accounts that had logged in with cms at least once but if your account is created with worldserver console and you haven't logged at least once in cms it still missing some records (in account data) and without those that specific accounts will still trow those errors, actually even more when you search for them in admin panel.

**Comment by Err0r1** [comment]
Why should one create accounts per console?
but I can't change anything about it
the worldserver cannot access fusiongen

in order for accounts to be synchronized, you have to log in at least once

**Comment by CraftedRO** [comment]
indeed
