### ISSUE TITLE
Teleport hub required faction feature doesn't works

### ISSUE THREAD

**Issue by CraftedRO** [FusionGen/FusionGEN#168]
Teleport hub required faction feature doesn't works so even if you set horde only the alliance characters can still see and use horde teleport locations and vice versa.

![sqsq](https://user-images.githubusercontent.com/24683355/216591283-1265132f-a41b-4e8a-9ed0-f6c94918ee3d.PNG)

**Comment by CraftedRO** [comment]
well after few more tests it seems it doesn't actually teleport you but you will see some unrelated message and maybe we can hide unusable locations idk

![sqsq](https://user-images.githubusercontent.com/24683355/216593298-14000609-a5be-41ae-a04b-da77801c30f9.PNG)

**Comment by Err0r1** [comment]
I will take a look today evening
A lot ot meetings today >.>

**Comment by CraftedRO** [comment]
well this is just cosmetic as I see, not a thing

**Comment by Err0r1** [comment]
Fixed
