### ISSUE TITLE
Vote verification

### ISSUE THREAD

**Issue by Fullhouser** [FusionGen/FusionGEN#17]
Enabling vote verification does nothing at all. After properly voting on site (the one that supports this feature) doesnt do anything and you can still use vote button repeatedly (short version voting never counts). - tested with TOPG.org

OS: Windows Server 2016 Datacenter
Apache: 2.4.41
PHP: 7.1.33
DB: MySQL 8.0

**Comment by omghixd** [comment]
This system was broken about a year after FCMS's release. Nonetheless, good report. Would appreciate if you followed this format from now on =)

https://github.com/FusionGen/FusionGen/issues/2

**Comment by OMGhixD-OG** [comment]
Valuable Information:

This System was written with the intent of Topsites also helping and doing their part. The System requires a verification from the CMS by 50% and an verification from the topsite of choice by 50%.

Majority of all topsites that had Vote Verification quickly dropped support and fell behind on keeping the system up to date and to include it in newer versions of their topsite(s). This might also be relatively broken on current FGEN (Unsure, have not tested).

But all in all. It is a feature that is gonna be near impossible to support as we need information from the topsite as well to properly verify that the user voted. What currently is. Is the best we can do.

**Comment by Shadofiend** [comment]
for all vote sites is bug - confirm

**Comment by OMGhixD-OG** [comment]
If you are comment something. Comment something useful. Dont tell us stuff that we already know.

**Comment by disclosurez** [comment]
it seems the only callback working is topg.org, all the other sites callback is not working because of an issue there end.

**Comment by OMGhixD-OG** [comment]
> it seems the only callback working is topg.org, all the other sites callback is not working because of an issue there end.

The system was attempted to be popularized. But it kinda failed tbh, over the years people just didn't care about it (except the Server Staff that ran WoW Servers) overall for the TopSites its just more traffic. So i get their perspective of it but i do also get the annoyance caused towards the Server Owners as well.

**Comment by Err0r1** [comment]
since no voting site supports callback anymore and it works reliably, I'm closing here
