### ISSUE TITLE
Database need some improvements

### ISSUE THREAD

**Issue by CraftedRO** [FusionGen/FusionGEN#171]
well database can be converted to utf8mb4 something like this https://github.com/CraftedRO/FusionGen-SRP6-WotLK/commit/5b54a81cc24a89aaf7e1981566f6b0eb7e76be55
- myisam shoud be converted to innodb
- a single insert for things
- ideally when insert things woud be to specify again tables too, not just insert values.
- removed useless whitespaces for example on display id-s

I can do this but will be a long pr and hard to review.

**Comment by Err0r1** [comment]
You said it. it will be a long PW and a lot of detail work..
you can split it into several PRs maybe

**Comment by CraftedRO** [comment]
https://github.com/FusionGen/FusionGEN/pull/177
https://github.com/FusionGen/FusionGEN/pull/180
