### ISSUE TITLE
[WTF, BUG HACKS]

### ISSUE THREAD

**Issue by lastdarken** [FusionGen/FusionGen#18]
Hi

db again &  full , removed all databases

![wtf](https://user-images.githubusercontent.com/63067250/81592824-c32b5180-93d3-11ea-8374-e7027f2d2ec5.jpg)

info:
Direct Admin, linux.
Mysql connect rank access = Full
Allowed ip in vps firewall; just for ip host
User: ******
Pass: *******

---

Admin Panel:
User: ***** 
Pass: ****
Security:  ******
Permissions: files 0644.

version:
https://github.com/FusionGen/FusionGen/commit/9a9320ad098f81514c33feb84488410904759028

GG

**Comment by alexandre433** [comment]
I've just blured you're passwords.

DO NOT share your passwords EVER, ANYWHERE, they are yours, not ours.

Another thing, NEVER give a website FULL MYSQL ACCESS, why? Because of this..

We will look into the current project and check what we missed, further than that I cannot help you more.. unless you have the access logs to your mysql database, that would be nice to check.

**Comment by lastdarken** [comment]
Ok .

It was for testing, access.

hacker can again use injected to mysql.

**Comment by disclosurez** [comment]
make sure you have hourly backups for this purpose, disable avatar uploads & forum upload

**Comment by omghixd** [comment]
You gotta understand a couple of things. It takes time to patch this as we are adding a fix then we need to wait for a test.

and this "hacker" is not a hacker.. its an automated system performing this injection.

**Comment by lastdarken** [comment]
@disclosurez

I have Backups....

**Comment by omghixd** [comment]
Good that you have that, he should mention it regardless as this project is for a big community and others may not be aware :)

**Comment by Jiinx** [comment]
info:
Direct Admin, linux.
Mysql connect rank access = Full
Allowed ip in vps firewall; just for ip host

So you are saying that some was able to remotely connect to wipe your your databases even though you only allows access via the host IP? Have you check access logs for the server? 

The details of what you say happened and how you say your system is set up doesn't line up. 

Also, I see you are using PHPMyAdmin
https://www.cvedetails.com/vulnerability-list/vendor_id-784/Phpmyadmin.html

**Comment by lastdarken** [comment]
Hi

just host ip can connect to mysql / databases server:

example:
sudo ufw allow from 127.0.0.1 to any port 3306
sudo ufw deny 3306

**Comment by lineagedr** [comment]
@lastdarken Archive application/logs folder and send it

**Comment by lastdarken** [comment]
I removed cms...!
