### ISSUE TITLE
Unknown column 'invoice_number' in 'field list'

### ISSUE THREAD

**Issue by CraftedRO** [FusionGen/FusionGEN#183]
When you click on donate (any value) buttons you get this error because there's no such a column in paypal_logs db

![donate](https://user-images.githubusercontent.com/24683355/222916780-98df4bf1-c5a4-4f71-a900-a79ed41de521.PNG)

**Comment by Err0r1** [comment]
Oh, forgot to change the paypal logs table too
I will upload it when I'm at home

**Comment by CraftedRO** [comment]
character set utf8 (simple) is not valid for collate utf8mb4_unicode_ci

**Comment by Err0r1** [comment]
Stupid encoding stuff
Fixed

**Comment by CraftedRO** [comment]
yea also in heidi CHARACTER SET at the end line does generate a warning, not sure how important and that's why I choosed CHARSET instead at:

> ) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET =

**Comment by CraftedRO** [comment]
yea
