### ISSUE TITLE
Problem logging into the account

### ISSUE THREAD

**Issue by poryagholami** [FusionGen/FusionGEN#191]
**Is your feature request related to a problem? Please describe.**
Nothing happens on this page when I enter the username and password
It can only be entered from the top menu

**Describe the solution you'd like**
It should be entered into the account when we enter the user account and password

**Describe alternatives you've considered**
Edit module

**Additional context**
![image](https://user-images.githubusercontent.com/52524476/225615658-186f27f3-21ff-4c63-a438-71d6ddf791e7.png)

**Comment by Err0r1** [comment]
More info: sidebox info/login module

**Comment by CraftedRO** [comment]
yea the issue is valid you can't login atm whitin Sidebox: user info & log in

![sqsq](https://user-images.githubusercontent.com/24683355/225622987-029bcccc-f8ae-41be-b333-f943bf762466.PNG)

**Comment by CraftedRO** [comment]
seems captcha related
