### ISSUE TITLE
The problem of the position of the top menus

### ISSUE THREAD

**Issue by poryagholami** [FusionGen/FusionGEN#192]
**Is your feature request related to a problem? Please describe.**
I change their position, but it doesn't change

**Describe the solution you'd like**
Should be edited from right to left
Or vice versa
Do it right

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/52524476/225617757-6eb010d6-b050-4c9b-be32-827e30726eac.png)

**Comment by Err0r1** [comment]
Invalid, its working

**Comment by poryagholami** [comment]
> this is most likely because he didn't properly cleared browser cache

I tried with another browser
It was probably fixed 1-2 days ago
