### ISSUE TITLE
Problem new menu

### ISSUE THREAD

**Issue by poryagholami** [FusionGen/FusionGEN#193]
**Is your feature request related to a problem? Please describe.**
new menu It does not make a new one

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![WoWScrnShot_031323_214346 1](https://user-images.githubusercontent.com/52524476/225647844-b2664616-450a-4ee4-bae9-b3938ca8f00c.jpg)

**Comment by CraftedRO** [comment]
this is not yet completed, the sweetalert with changes saved or smth like this do not appear so that's why user got distracted, and you had to manually refresh the page to see the changes.
