### ISSUE TITLE
Problem change title

### ISSUE THREAD

**Issue by poryagholami** [FusionGen/FusionGEN#194]
**Is your feature request related to a problem? Please describe.**
change Problem

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![WoWScrnShot_031323_214346 1](https://user-images.githubusercontent.com/52524476/225653440-b68d706b-4bfd-4feb-91a9-8523d4099974.jpg)
![WoWScrnShot_031323_214346 1](https://user-images.githubusercontent.com/52524476/225653996-98a8271f-05ab-4eff-8123-8db75c8a44dc.jpg)

**Comment by CraftedRO** [comment]
I can't see the screenshoots you uploaded

**Comment by poryagholami** [comment]
> I can't see the screenshoots you uploaded

see now

**Comment by CraftedRO** [comment]
I was able to change title of my sidebox and it saved, can you try please without special Iranian I guess characters ?

**Comment by poryagholami** [comment]
> I was able to change title of my sidebox and it saved, can you try please without special Iranian I guess characters ?

![image](https://user-images.githubusercontent.com/52524476/225658740-174aa2e4-00fa-4ce2-b9bb-795a5452c152.png)

**Comment by poryagholami** [comment]
> I was able to change title of my sidebox and it saved, can you try please without special Iranian I guess characters ?

It changes from the database, but try from inside the site

**Comment by poryagholami** [comment]
> yea I finnaly see what you mean :) select from Sidebox module your battleground module again and try to save

yes

**Comment by CraftedRO** [comment]
is still not completed, it need workaround too
