### ISSUE TITLE
Erorr Modules sidebox_poll

### ISSUE THREAD

**Issue by poryagholami** [FusionGen/FusionGEN#195]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![WoWScrnShot_031323_214346 1](https://user-images.githubusercontent.com/52524476/225661660-429e7fa1-161a-4971-8daa-2ba81fbd6d15.jpg)

**Comment by CraftedRO** [comment]
this is happen only when no data in db (no poll created in: website>manage polls), after you create one it works fine

**Comment by Err0r1** [comment]
https://github.com/FusionGen/FusionGEN/commit/40ac0e89ad0791e5fc865685026e2ed9f40049f2
