### ISSUE TITLE
4 Error to fix

### ISSUE THREAD

**Issue by T3llorista** [FusionGen/FusionGEN#202]
1º fix
in acp view the account the expasion no are Dragonflight
![Captura de pantalla 2023-03-23 222759](https://user-images.githubusercontent.com/123669924/227370533-3ccf4792-b7d2-4d4e-a6cb-506018e9ae42.png)
2º fix 
to change Languages default web to spanish and go to home index revived a error (see the photo 2)
![imagen_2023-03-23_223200339](https://user-images.githubusercontent.com/123669924/227368385-2a4d32a6-e42a-4167-96b7-f423872a5149.png)
![imagen_2023-03-23_223419450](https://user-images.githubusercontent.com/123669924/227368913-ddf261d5-d020-4b78-86ae-091cf0f93cdc.png)
3º fix
why i create a console command in item store this ".modify money 1000" and buy but recived error 
![imagen_2023-03-23_225056905](https://user-images.githubusercontent.com/123669924/227372496-683effc1-68d6-4645-8969-c498bb57193c.png) and other command work prefect. i test ".kick character" and .modify money 1000 work perfect in console 
4ºfix 
when i create a item in store recived a error "table item_template not exist" in emulator trinity core dragonflight. i copy the table for 3.3.5 and work perfect and i can create items 

thz to the coder for this proyect :-)

**Comment by Err0r1** [comment]
1: yes, because the emulator has no DF expansion (SL is the highest emulator atm)
2: Ty, will fix it asap

**Comment by CraftedRO** [comment]
I don't know in what console have you tried but in latest 3.3.5 trinitycore that command result this:

![image](https://user-images.githubusercontent.com/24683355/227389580-0329c283-8a9b-4c5e-8774-4b195fd02369.png)

**Comment by Err0r1** [comment]
Create for every problem a new issue pls
it makes no sense to have an issue with 50 problems in it
