### ISSUE TITLE
settings in admin panel not working

### ISSUE THREAD

**Issue by MrLanovskiy** [FusionGen/FusionGEN#208]
Hello.  Not clickable settings in the admin panel, please help.

**Comment by Err0r1** [comment]
can you give more infos pls?

**Comment by Err0r1** [comment]
the first thing you should do is fix soap
2nd this is the dashboard
there is nothing to click around

**Comment by Err0r1** [comment]
fix soap, then the dashboard will also load faster

**Comment by htc16** [comment]
I'm using the latest version of fusiongen, and for me everything is fine.

**Comment by MrLanovskiy** [comment]
Work, Thank you for help.
