### ISSUE TITLE
Multiple orders of the same item, results in only 1 item being delivered

### ISSUE THREAD

**Issue by disclosurez** [FusionGen/FusionGEN#21]
- What are you specifically reporting (one report per issue):
Multiple orders of the same item, results in only 1 item being delivered (using web shop)
-  How do we replicate this issue that you are encountering?`:
Order multiple of the same item, e.g. 2x item A. Only 1x of Item A will be delivered.
- Are you hosting FusionGen on a All-in-One Package or an Webhost:
 webhost ubuntu 20.04 lts
- Have you made any personal modifications? If so, What?:
just css 
- PHP Version:
 MySQL 8, Php 7.1
- Core?
Azerothcore Latest version, using SOAP

**Comment by omghixd** [comment]
Unable to reproduce. Alltho please ensure that you are running on MySQL 5.7 instead of MySQL 8.0

FusionCMS(GEN) was never meant to run on 8.0 and shouldn't be tested on those environments it was not written for.

**Comment by OMGhixD-OG** [comment]
Please follow instructions from here: https://github.com/FusionGen/FusionGEN/issues/40
