### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by T3llorista** [FusionGen/FusionGEN#211]
when change the languages to spanish default web 
![Captura de pantalla 2023-03-23 223152](https://user-images.githubusercontent.com/123669924/229873894-fea2e4be-bebd-4ae5-9c87-87cb5d120104.png)
and press to home ico, look the error
![Captura de pantalla 2023-03-23 223408](https://user-images.githubusercontent.com/123669924/229874301-34223a4a-9eb7-4ffa-b400-d7c0b420644f.png)

**Comment by CraftedRO** [comment]
I tried to reproduce this but coudn't, not sure what article or custom page you added.

**Comment by T3llorista** [comment]
nothing, all my web are defaul download of github wich the news create of default. change all to spanish languages (default web to spanish and click spanish at home to reproduce the error)
![Captura de pantalla 2023-04-04 200836](https://user-images.githubusercontent.com/123669924/229880830-6af1ed4d-4710-4e72-b337-aa09ed87e715.png)

**Comment by CraftedRO** [comment]
ok after deleting the cache, it appeared

**Comment by Err0r1** [comment]
Fixed. https://github.com/FusionGen/FusionGEN/commit/6ecdc327a2bc74c81dbd3489a5af3230da45059e
