### ISSUE TITLE
Background color problem for later characters

### ISSUE THREAD

**Issue by poryagholami** [FusionGen/FusionGEN#216]
**Is your feature request related to a problem? Please describe.**
![d31189027ba7a94d8d316982c41f1411](https://user-images.githubusercontent.com/52524476/233135638-31f23071-5edc-41ab-afb8-8bb050cb9888.jpg)

**Describe the solution you'd like**
Background color should be added for all the characters that are added

**Describe alternatives you've considered**

**Additional context**

**Comment by Err0r1** [comment]
It striped, if there r 3 chars, theres a background again

**Comment by CraftedRO** [comment]
If people start opening issues with the cosmetic stuff then I think cms is already better.

**Comment by CraftedRO** [comment]
If people start opening issues about cosmetic stuff then I think cms is already better.
