### ISSUE TITLE
Problem transferring the avatar page

### ISSUE THREAD

**Issue by poryagholami** [FusionGen/FusionGEN#217]
**Is your feature request related to a problem? Please describe.**
https://user-images.githubusercontent.com/52524476/233136676-e4f45d35-2358-41ac-9c62-39bd6bfa6f9c.mp4
When we select the avatar, it does not return to the UCP page
**Describe the solution you'd like**
It should return to the ucp page

**Describe alternatives you've considered**

**Additional context**

**Comment by Err0r1** [comment]
Not rlly an "issue"
Idk why it jumps to the top, but there shouldn't be redirect to the UCP

**Comment by CraftedRO** [comment]
it jumps to the top because of the # at the end of the link

**Comment by CraftedRO** [comment]
it jumps to the top because of the # at the end of the link:

`<a href="#" data-avatar-id="22" class="my_avatar avatar_current" onclick="Avatar.change(this)" style="background-image: url('http://localhost/application/images/avatar/staff_12.jpg');"></a>`

**Comment by CraftedRO** [comment]
also players avatars are kinda ugly

**Comment by poryagholami** [comment]
> also players avatars are kinda ugly

lol
