### ISSUE TITLE
The built-in text editor does not apply formatting to pages

### ISSUE THREAD

**Issue by disclosurez** [FusionGen/FusionGEN#22]
- What are you specifically reporting (one report per issue):
The inbuilt text editor does not apply formatting to pages, only ITALICS works, colours etc do not work. HTML does not even save to the DB.
-  How do we replicate this issue that you are encountering?`:
Create a blank page using the default-wotlk theme and apply formatting to the text, notice none of the text formatting is applied.
- Are you hosting FusionGen on a All-in-One Package or an Webhost:
 webhost ubuntu 20.04 lts
- Have you made any personal modifications? If so, What?:
just css 
- PHP Version:
 MySQL 8, Php 7.1

**Comment by lastdarken** [comment]
Confirm!

**Comment by R4dSec** [comment]
Confirmed!

**Comment by OMGhixD-OG** [comment]
Should be resolved as of commit https://github.com/FusionGen/FusionGEN/commit/40d0ae7dbe4b306bb5ef3a3bb9d300ee61a7d5cd

Requesting a test.

**Comment by disclosurez** [comment]
confirmed fixed ty

**Comment by OMGhixD-OG** [comment]
Reopened due to security risk being noticed.

Commit https://github.com/FusionGen/FusionGEN/commit/40d0ae7dbe4b306bb5ef3a3bb9d300ee61a7d5cd & https://github.com/FusionGen/FusionGEN/commit/55ec9c1f0fe43413873aaa4beb60d3855112309a has also been reverted.

We need to resolve this differently.

**Comment by mdjong1** [comment]
@OMGhixD-OG related to this issue; there's two things we could do (imo).

(my preference) If the account is an admin account; they should be allowed to POST anything (without escaping stuff) because the expectation is that an admin account won't try to XSS their own website.

Other option is allowing only TinyMCE things to go through; but if a rando gets access to the TinyMCE editor it means they mess shit up.

**Comment by OMGhixD-OG** [comment]
@disclosurez are you experiencing anything different/new after this commit ? 
https://github.com/FusionGen/FusionGEN/pull/58

**Comment by mdjong1** [comment]
> @disclosurez are you experiencing anything different/new after this commit ?
> #58

Unfortunately #58 won't have an effect on this issue, but looking into that one as well. Bit more tricky

**Comment by Hamarz** [comment]
User written html should never be saved on the database or pre-existing list of allowed html tags only.

**Comment by Err0r1** [comment]
https://github.com/FusionGen/FusionGEN/issues/116

Fixed
