### ISSUE TITLE
News article

### ISSUE THREAD

**Issue by MarkAvrely** [FusionGen/FusionGEN#220]
Hello, can't create new news article. When adding news, nothing happend, page reloading and my news empty.

News "Welcome to your new website! This news article will disappear as soon as you add a new one." still appear.
default language EN.
what iam doing wrong?

**Comment by Err0r1** [comment]
Check browser console and disable all adblockers
Some of them are blocking news (stupid tools)

**Comment by MarkAvrely** [comment]
i'am using mozilla, i dont have any adblockers, i'am trying to clear cookies but still doesnt work :(

**Comment by Err0r1** [comment]
Check your error log and browser console then

**Comment by CraftedRO** [comment]
on of the reasons why mozilla sux

**Comment by CraftedRO** [comment]
one of the reasons why mozilla sux
