### ISSUE TITLE
(Captcha) problem In the module sidebox_info_login

### ISSUE THREAD

**Issue by poryagholami** [FusionGen/FusionGEN#221]
**Is your feature request related to a problem? Please describe.**
When I enter the code by mistake, it does not change
And when I enter the same again correctly
He enters the account

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by poryagholami** [comment]
I mean, when you make a mistake once, the code should be changed, but it doesn't happen, and the bot can easily empty it.

**Comment by Err0r1** [comment]
So it works exactly as it should
You can reset it if u click on the butto..

**Comment by poryagholami** [comment]
It should change automatically after each error

**Comment by Err0r1** [comment]
Why?

**Comment by poryagholami** [comment]
Once you make a mistake, it should automatically change. If it doesn't change, it doesn't matter because the robot will empty it

**Comment by poryagholami** [comment]
If you pay attention, when you create a Discord account or anything, there is a captcha to know if you are a robot or not
If you make a mistake, it will bring you another picture

**Comment by Err0r1** [comment]
Why should it change automatically if you make a typo?
Google doesn't do that
Discord does it
So it's up to each project

**Comment by poryagholami** [comment]
If you make a mistake
This password must be changed
What is the need if it does not change?

**Comment by Err0r1** [comment]
Do you still have to solve it to log in
If you type it wrong and the captcha changes, it's not automatically more secure
You have to solve the captcha anyway. Whether it is the same or different makes no difference
The login attempt is counted and blocked if there are too many

**Comment by poryagholami** [comment]
However, I think that needs to change
Because all captchas change, everywhere I saw

**Comment by Err0r1** [comment]
Nicht alle 🤷‍♂️ 
If you want it that way, feel free to open a PR
