### ISSUE TITLE
Item description

### ISSUE THREAD

**Issue by MarkAvrely** [FusionGen/FusionGEN#223]
greetings. i need to change language descr of all item to german, is it possible? or i have to edit all items in mysql? 
![description](https://user-images.githubusercontent.com/132078458/235720516-022be0c2-d944-40f7-b5ac-029a0b67435b.jpg)

**Comment by CraftedRO** [comment]
This does not belong here in issue tracker, most likely the item descriptions are taken from world database of your emulator.

**Comment by MarkAvrely** [comment]
got it. thx you

**Comment by CraftedRO** [comment]
you can ask your other thoughts on the discord channel
