### ISSUE TITLE
Server shows offline (Azerothcore)

### ISSUE THREAD

**Issue by Anntonix** [FusionGen/FusionGEN#229]
Hello, so everything is setup, shop works, acc creations etc, ports are open players can connect but no matter what the server status remains offline. I'm using AC 3.3.5a SRP6 Soap

Anyone else with this problem?

**Comment by Err0r1** [comment]
Is the realmID in authDB -> realmlist the same as in fusionDB -> realms?

**Comment by Err0r1** [comment]
Can you check your log in /application/logs ?

**Comment by Anntonix** [comment]
no errors

**Comment by Err0r1** [comment]
Do u use a vps/dedicated or a web hosting?
Some hosters disabled fsockopen function

**Comment by Anntonix** [comment]
dedicated

**Comment by CraftedRO** [comment]
has this issue been solved ?
