### ISSUE TITLE
Donate Panel SSL Certificate ? 

### ISSUE THREAD

**Issue by cyberpro98** [FusionGen/FusionGEN#234]
Hi, when i am trying to click on Donate 10eur it drops me on error page .. 
There are the errors : 
PayPal\Exception\PayPalConnectionException: SSL certificate problem: unable to get local issuer certificate in C:\inetpub\wwwroot\vendor\paypal\rest-api-sdk-php\lib\PayPal\Core\PayPalHttpConnection.php:186 Stack trace: #0 C:\inetpub\wwwroot\vendor\paypal\rest-api-sdk-php\lib\PayPal\Auth\OAuthTokenCredential.php(252): PayPal\Core\PayPalHttpConnection->execute() #1 C:\inetpub\wwwroot\vendor\paypal\rest-api-sdk-php\lib\PayPal\Auth\OAuthTokenCredential.php(280): PayPal\Auth\OAuthTokenCredential->getToken() #2 C:\inetpub\wwwroot\vendor\paypal\rest-api-sdk-php\lib\PayPal\Auth\OAuthTokenCredential.php(216): PayPal\Auth\OAuthTokenCredential->generateAccessToken() #3 C:\inetpub\wwwroot\vendor\paypal\rest-api-sdk-php\lib\PayPal\Auth\OAuthTokenCredential.php(166): PayPal\Auth\OAuthTokenCredential->updateAccessToken() #4 C:\inetpub\wwwroot\vendor\paypal\rest-api-sdk-php\lib\PayPal\Handler\RestHandler.php(82): PayPal\Auth\OAuthTokenCredential->getAccessToken() #5 C:\inetpub\wwwroot\vendor\paypal\rest-api-sdk-php\lib\PayPal\Transport\PayPalRestCall.php(75): PayPal\Handler\RestHandler->handle() #6 C:\inetpub\wwwroot\vendor\paypal\rest-api-sdk-php\lib\PayPal\Common\PayPalResourceModel.php(104): PayPal\Transport\PayPalRestCall->execute() #7 C:\inetpub\wwwroot\vendor\paypal\rest-api-sdk-php\lib\PayPal\Api\Payment.php(571): PayPal\Common\PayPalResourceModel::executeCall() #8 C:\inetpub\wwwroot\application\modules\donate\models\Paypal_model.php(167): PayPal\Api\Payment->create() #9 C:\inetpub\wwwroot\application\modules\donate\controllers\Donate.php(34): Paypal_model->getDonate() #10 C:\inetpub\wwwroot\system\core\CodeIgniter.php(537): Donate->index() #11 C:\inetpub\wwwroot\index.php(250): require_once('...') #12 {main}

I am using an IIS Web Server.
Php Version 8.1.20

**Comment by Ferreira9006** [comment]
This issue is not related to FusionGEN.
It's caused by your webserver (IIS).

I'd mark this issue as invalid.

**Comment by CraftedRO** [comment]
https://www.paypal-community.com/t5/REST-APIs/Error-Got-Http-response-code-401-when-accessing-https-api-paypal/m-p/3051364/highlight/true#M8377
