### ISSUE TITLE
PHP Error index becom to slowed pages

### ISSUE THREAD

**Issue by Shadofiend** [FusionGen/FusionGEN#25]
Have php error indexs for characters with "/"
<details>
le="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">
A PHP Error was encountered
Severity: Warning

Message: call_user_func_array() expects parameter 1 to be a valid callback, class 'Error' does not have a method 'index'

Filename: core/CodeIgniter.php

Line Number: 356

�
</details>

--

This can to slowed pages..

https://www.cruel-wow.com/register/tst/qw/a
https://www.cruel-wow.com/register/tst/qw/qc/login/select/unicode/
https://www.cruel-wow.com/login/1/2/3/4/5/6/7/8/9/10/.
https://www.cruel-wow.com/login/1/2/3/4/5/6/7/8/9/10/00//no/yes/

For fix , if selected Characters unrelated to the system, get to -> 404 page.

**Comment by omghixd** [comment]
What platform are you running on? 

Xampp? Webhost?

We require more information.

**Comment by OMGhixD-OG** [comment]
Gonna assume that this is related to the user(s) setup rather than the CMS's code. 

This is usually taken care of by the properties set by the user / hosting provider.
And this has not been a widely spread issue and has not been reported nor confirmed by multiple users.

//Closed
