### ISSUE TITLE
Bug Armory Image

### ISSUE THREAD

**Issue by Destructor** [FusionGen/FusionGEN#269]
Hi,

On the armory after a click on item and go back item show "?"

![image](https://github.com/FusionGen/FusionGEN/assets/1570770/38db7a8a-7e0c-486a-8b25-82af61fddaa8)

![image](https://github.com/FusionGen/FusionGEN/assets/1570770/da3e3f0d-efd1-49a9-a585-89b8d914285c)

![image](https://github.com/FusionGen/FusionGEN/assets/1570770/a5912966-4560-42d9-a168-b56bb9fd9bc4)

**Comment by Destructor** [comment]
The error is caused by the system cache
![image](https://github.com/FusionGen/FusionGEN/assets/1570770/ef326dab-1112-41d4-88c2-9e87a55c1498)

**Comment by CraftedRO** [comment]
have you imported [Item_icons.sql](https://github.com/FusionGen/FusionGEN/blob/main/install/SQL/optional/item_icons.sql) ?

**Comment by Destructor** [comment]
Yes sorry for delay
![image](https://github.com/FusionGen/FusionGEN/assets/1570770/6c233b90-5d3c-41f4-ba26-9e7085d65847)
