### ISSUE TITLE
Error on Register account

### ISSUE THREAD

**Issue by T3llorista** [FusionGen/FusionGEN#284]
i Used the last versión FusionGen and last versión Trinity Core. This is a error when i create account in web 
![imagen_2024-01-11_184533076](https://github.com/FusionGen/FusionGEN/assets/123669924/c2c1603c-010b-4553-9814-341d56fe81d1)

**Comment by CraftedRO** [comment]
https://github.com/FusionGen/FusionGEN/issues/210
