### ISSUE TITLE
.htaccess fix for wamp server

### ISSUE THREAD

**Issue by Ramys** [FusionGen/FusionGEN#301]
Options +FollowSymLinks -Indexes
RewriteEngine On
RewriteCond %{HTTP:Authorization} .
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]

**Comment by CraftedRO** [comment]
is there a problem with existent .htaccess in wamp ?

**Comment by Ramys** [comment]
> is there a problem with existent .htaccess in wamp ?

yes, this previous configuration is not accepted.
After installation, you simply cannot navigate to other folders on the website.

**Comment by CraftedRO** [comment]
was rewrite_module enabled when you tested it ?

**Comment by CraftedRO** [comment]
can you test if this PR will fix your problem ?
