### ISSUE TITLE
[SOLUTION] mysqli_error() expects parameter 1 to be mysqli, bool given

### ISSUE THREAD

**Issue by omghixd** [FusionGen/FusionGen#33]
> So i am receiving the error:
> A PHP Error was encountered
> Severity: Warning
> Message: mysqli_error() expects parameter 1 to be mysqli, bool given
> Filename: mysqli/mysqli_driver.php
> Line Number: 458

**Solution:** This is happening because the CMS is attempting to use the data within a column called username_characters_override and that column is most likely populated with the value NULL.

So, Open your MySQL Database through a SQL Editor (Example: Heidisql). Head to your FusionGEN Database and access table Realms and fill out the columns "Override" with the MySQL Credentials you entered upon installing the CMS (NOTICE: this account will need global privileges.)

**Comment by brizleir** [comment]
facing same problem but i got this one.
Warning: mysqli_error() expects parameter 1 to be mysqli, string given in.

this is the code:
<?php

$server_name="localhost";
$username = "root";
$password = "";
$db = "myDB";

$conn = mysqli_connect($server_name, $username, $password, $db);

if(!$conn){
    die("could not connect ").mysqli_error();
}
else{
    echo "Connected successfully";
}

mysqli_select_db($conn ,$db);
session_start();

 $sql = "INSERT INTO userlogin(name,password) 
 VALUES ('$_POST[user] ','$_POST[password])'";
 if(!mysqli_query($conn,$sql)){
     echo("Error : " .mysqli_error($sql));
    } 
 else{
     echo "successfully signed in 😁";

 }
 mysqli_close($conn);
?>

**Comment by OMGhixD-OG** [comment]
> facing same problem but i got this one.
> Warning: mysqli_error() expects parameter 1 to be mysqli, string given in.
> 
> this is the code:

Please make your own BugReport, this is a solution issue and not for further reporting :)

PS: Above comment and or new comments will be deleted in 2-8 days.
