### ISSUE TITLE
Excuse me, how should I use this? I can't see where to set the parameters.

### ISSUE THREAD

**Issue by 1825679767** [FusionGen/FusionGEN#335]
### Description

Excuse me, how should I use this? I can't see where to set the parameters.

### Expected behaviour

Excuse me, how should I use this? I can't see where to set the parameters.

### Error log/notice

Excuse me, how should I use this? I can't see where to set the parameters.

### Screenshots

Excuse me, how should I use this? I can't see where to set the parameters.

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### FusionGEN rev. hash/commit

Excuse me, how should I use this? I can't see where to set the parameters.

### Webserver

- OS: [e.g. Debian 11]
- HTTP server: [e.g. Apache 2.4]
- PHP version: [e.g. PHP 8.1]
- MySQL server: [e.g. Mariadb 10.5.2]

### Additional context

Excuse me, how should I use this? I can't see where to set the parameters.

**Comment by CraftedRO** [comment]
Just copy the files inside your webserver www root or htdocs then just start the installer in browser following the installation wizard https://www.youtube.com/watch?v=hBqcF2IZ7gw

**Comment by 1825679767** [comment]
Thank you very much. It would be even better if Chinese were supported.
