### ISSUE TITLE
I hope a Chinese version can be added. Thank you very much.

### ISSUE THREAD

**Issue by 1825679767** [FusionGen/FusionGEN#336]
### Description

I hope a Chinese version can be added. Thank you very much.
Or you can let me know where the language files are stored, and I can help with the translation to Chinese.

### Describe the solution you'd like

I hope a Chinese version can be added. Thank you very much.
Or you can let me know where the language files are stored, and I can help with the translation to Chinese.

### Additional context

I hope a Chinese version can be added. Thank you very much.
Or you can let me know where the language files are stored, and I can help with the translation to Chinese.

**Comment by mdjong1** [comment]
https://github.com/FusionGen/FusionGEN/tree/main/system/language/simplified-chinese

**Comment by CraftedRO** [comment]
he probably mean smth like this https://github.com/FusionGen/FusionGEN/pull/276/files

**Comment by 1825679767** [comment]
After the setup is complete, you enter the main interface where there is no option for Simplified Chinese. Additionally, clicking on login or register prompts "No input file specified," and the webpage does not function。
![Uploading 1724318207678.jpg…]()

**Comment by 1825679767** [comment]
![1724318207678](https://github.com/user-attachments/assets/4a59015b-eedc-4a6b-a461-e624eddfce35)

**Comment by CraftedRO** [comment]
yeah because noone created a pull request for that, as I said [here](https://github.com/FusionGen/FusionGEN/issues/336#issuecomment-2297496555)

**Comment by 1825679767** [comment]
Additionally, clicking on login or register prompts "No input file specified," and the webpage does not function。

**Comment by CraftedRO** [comment]
> Additionally, clicking on login or register prompts "No input file specified," and the webpage does not function。

can you test again after updating to latest .htaccess file please ?

**Comment by 1825679767** [comment]
> > 此外，单击登录或注册提示“未指定输入文件”，并且网页无法运行。
> 
> 请在更新到最新的 .htaccess 文件后再次测试吗？

Thank you very much; it's working fine now.
