### ISSUE TITLE
send posting by txt colors buged.

### ISSUE THREAD

**Issue by lastdarken** [FusionGen/FusionGen#37]
Posting news with text colors , is bug!

Can't use txt to posts by set color.

**Comment by favorit5503** [comment]
We need more info. A picture. And some details are missing. What PhP? What theme?

**Comment by Dreacus** [comment]
the same issue is mentioned here : [https://github.com/FusionGen/FusionGen/issues/22](url)

**Comment by BarbzYHOOL** [comment]
it's inside the core files (not the module) or the codeigniter files if i recall, need to edit something that strips some special characters like < \ " or another
