### ISSUE TITLE
SHA_PASS_HASH problem, need SRP6 support for fresh TrinityCore

### ISSUE THREAD

**Issue by DykeRz** [FusionGen/FusionGen#41]
Hello, i installed the CMS on my web hosting, so it's don't working for me, because TrinityCore using srp6 system password's, but this CMS using sha_pass_hash, so i can't log in account in CMS

error:

A Database Error Occurred
Error Number: 1054

Unknown column 'sha_pass_hash' in 'field list'

SELECT id id, username username, sha_pass_hash password, email email, joindate joindate, last_ip last_ip, last_login last_login, expansion expansion FROM account WHERE username = 'dyker'

Filename: /var/www/u1130362/data/www/wowcolossus.ru/models/external_account_model.php

Line Number: 72

**Comment by omghixd** [comment]
http://www.ac-web.org/forums/showthread.php?238573-FusionCMS-SRP6-support

Darksider resolved this. I personally don't feel like committing it without permission. So i'll request permission to add it.
If he says no then there isn't much i can do.

**Comment by Shadofiend** [comment]
Confirm for FusionGen

**Comment by omghixd** [comment]
This has been updated and as of commit https://github.com/FusionGen/FusionGen/commit/ed0222b3f4b658871d0932b9b563537939a29b14

A new branch was added to the repo
see: https://github.com/FusionGen/FusionGen/tree/master-srp6

**Comment by darkenam** [comment]
Hi i use this version 
https://github.com/FusionGen/FusionGen/tree/master-srp6

for last zerothcore but not worked

Error Number: 1054

Unknown column 'sha_pass_hash' in 'field list'

SELECT id id, username username, sha_pass_hash password, email email, joindate joindate, last_ip last_ip, last_login last_login, expansion expansion FROM account WHERE id = 0

Filename: /home/public_html/4/models/external_account_model.php

Line Number: 68
