### ISSUE TITLE
JS doesn't work

### ISSUE THREAD

**Issue by kepo123** [FusionGen/FusionGen#44]
I just installed fresh FusionGEN and any function with JS doesn't work. (realm status, store - expand the categories, armory )

Browser console: https://prnt.sc/wjxrdc
Hosting on Windows Server 2012 with WAMP - PHP 7.1.33 / Apache 2.4
MySQL 5.7 (MySQL Workbench) (yep, wamp is only for the website)
All modules and extensions are enabled

Installation was success. There are no custom changes.

**Comment by omghixd** [comment]
This has been fixed as of commit 

1.) https://github.com/FusionGen/FusionGen/commit/97433e425cb88791706f63bd53aaa72242566ecc
2.) https://github.com/FusionGen/FusionGen/commit/29b53e8b0ba13fea256a5ffc75f357b44d90e6b8
3.) https://github.com/FusionGen/FusionGen/commit/57b7b6b33dc6d6145de24097c1993b81c551dd28
