### ISSUE TITLE
SRP6 Modifications Are Required [Currently Broken] + Possible Fix

### ISSUE THREAD

**Issue by OMGhixD-OG** [FusionGen/FusionGEN#45]
**Describe the bug**

According to another user whom are experimenting with SRP6 (Latest TC Registration Method). It has been reported that there are minor parts of the code that breaks and or causes immense delay on the CMS and the related branch. User has also provided a fix which can be found on the thread where the SRP6 originally originates from. This Report is merely for documentation purposes.

**To Reproduce**

1. No Reproducable Steps

**Expected behavior**

No further description than what is explained above.

**Screenshots**

No Screenshots

**Desktop (please complete the following information):**

OS: Windows/Unix (or anything can that can host this FCMS/GEN
Browser: Any
Version: Unknown

**Additional context**

No further additional context was added.

Fix Method was as given per DM and read on the related thread to be as following (from start to finish)

File located at: "application/third_party/MX/Controller.php"
Line: 125
Behaviour: Webserver would oftenly or all times give away a HTTP_COOKIE error.
Reason for behaviour: Unsure.

Fix
1.) Find said fail controller.php at the mentioned location above
2.) find 
if(column('account', 'password') == 'verifier' && column('account', 'salt')) 
replace both lines (the IF statement and $password = urldecode...)

3.) replace with 
if($password && column('account', 'password') == 'verifier' && column('account', 'salt')) // emulator uses srp6 encryption
$password = urldecode(preg_replace('~.(?:fcms_password=([^;]+))?~', '$1', @$_SERVER['HTTP_COOKIE']));

Memorable Mentions

Originally looks like this
if( && column('account', 'password') == 'verifier' && column('account', 'salt')) // emulator uses srp6 encryption

Should look like this
if($password && column('account', 'password') == 'verifier' && column('account', 'salt')) // emulator uses srp6 encryption

**Comment by OMGhixD-OG** [comment]
Strange. SRP6 Modifications seems to never have taken place in Controller.php

Added
"if($password && column('account', 'password') == 'verifier' && column('account', 'salt')) // Emulator Uses SRP6 Encryption." for further testing.

Report remains open until this issue is clearified.

For documentation. Please see commit https://github.com/FusionGen/FusionGEN/commit/a5ddad232b4363c78219f1f4a434d3284831726a

**Comment by Shadofiend** [comment]
For last TrinityCore Need To Updates.

Register / Login / Change Pass / Recovery Pass

**Comment by OMGhixD-OG** [comment]
This should be working as of commit https://github.com/FusionGen/FusionGEN/commit/43e6ba0e89eb0e884701cfef28c0a50a50ee2427 and https://github.com/FusionGen/FusionGEN/commit/4f6dadfa179c65bdc5f3b81dc3da060e2f4e84b4

requesting a new test.

**Comment by OMGhixD-OG** [comment]
Whelp, No response. So i'm gonna assume that did the trick and go ahead and close this report. 

Re-open or Open a new one if an issue within this system appears again.
