### ISSUE TITLE
 Very heavy!

### ISSUE THREAD

**Issue by Ramys** [FusionGen/FusionGEN#51]
**Describe the bug**
Installation everything seems fine, but when the page loads there is a slowness.

**To Reproduce**
1.very good, but very slow, looks heavy and does not load the page
2.even installing what you mentioned here https://github.com/FusionGen/php-7.1.33
**Expected behavior**
Even installing with the recommended php.
I'm using .https://www.wampserver.com/en/

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [e.g. chrome, brave]

**Additional context**
Heavy page, even in the localhost, it is impossible to load.

**Comment by OMGhixD-OG** [comment]
Please ensure that you are running the latest version of FGEN and try Laragon with php 7.1.33 instead. Wampserver and Xampp isn't exactly known to be "good" programs.

**Comment by Ramys** [comment]
> Please ensure that you are running the latest version of FGEN and try Laragon with php 7.1.33 instead. Wampserver and Xampp isn't exactly known to be "good" programs.

I will test immediately

**Comment by Ramys** [comment]
Same with https://laragon.org/ and https://github.com/FusionGen/php-7.1.33.

**Comment by OMGhixD-OG** [comment]
Go through this and ensure that this is also done

https://github.com/FusionGen/FusionGEN/issues/33

**Comment by Ramys** [comment]
MySQL Version: 5.7.31
PHP Version: 7.1.33
Laragon and Wampp (testing on both)
Latest FGEN Version (Yes/No): YES
Azerothcore :. https://github.com/azerothcore/azerothcore-wotlk
I will check this:.https://github.com/FusionGen/FusionGEN/issues/33

**Comment by Ramys** [comment]
![image](https://user-images.githubusercontent.com/5787076/105893365-c3b35900-5ff1-11eb-8e25-45c9962837c3.png)
Look this.
@OMGhixD-OG

**Comment by OMGhixD-OG** [comment]
This screenshot tells me nothing?

Come to our discord server instead.
