### ISSUE TITLE
Error at registration on a fresh Trinitycore

### ISSUE THREAD

**Issue by CraftedRO** [FusionGen/FusionGEN#55]
**Describe the bug**
Hi there , is there a chance to update trinity registration for a clean core , atm it does trow me this error at the end of installation (right after Im asked about owner username) and then everytime I try to register a new account .
**To Reproduce**
1. Go to '/register'
2. Click on 'create account' after you completed the installation

**Expected behavior**
Well I guess the registration shoud work well on a fresh TC.

**Screenshots**

![zzz](https://user-images.githubusercontent.com/24683355/111461760-4caf5c80-8726-11eb-8c6e-f2531e45c6a6.JPG)

**Desktop (please complete the following information):**
 - Windows 10 x64

**Smartphone (please complete the following information):**
 - PC
 - Windows 10 x64
 - Chrome
 - Version [browser version I guess > 89.0.4389.90 (Official version) (64 bit)]

**Additional context**
From what I know is something about they changed they'r registration tables , idk now is something about SRP6 and gmp extension .
If it does help Il let here a working [registration website](https://github.com/masterking32/WoWSimpleRegistration) whitch I tested it and it does work well , if u wanna check .

**Comment by CraftedRO** [comment]
PHP Version 7.1.33

**Comment by IceNet** [comment]
Please use SRP6 branch

https://github.com/FusionGen/FusionGEN/tree/master-srp6

**Comment by CraftedRO** [comment]
hmm ok I didn't saw that :)

**Comment by CraftedRO** [comment]
well now Im getting other error right after install
![zsq](https://user-images.githubusercontent.com/24683355/111465488-d6612900-872a-11eb-971a-aadba8ca0949.JPG)

**Comment by mdjong1** [comment]
Update the 'emulator' field in your `realms` table within the fusiongen db. In SRP6 the only options are `trinity_rbac_ra` or `trinity_rbac_soap`

**Comment by CraftedRO** [comment]
this thing shoudn't be done by itself when clean installing srp6 branch ?

**Comment by mdjong1** [comment]
If you cleaned your database too then you can only choose from those two options

**Comment by OMGhixD-OG** [comment]
> this thing shoudn't be done by itself when clean installing srp6 branch ?

No. You have chosen an emulator that does not exist. So the CMS doesnt have to correct anything, it is doing exactly as its told.

Do we have to update that list? i believe that question is rather clear to be answered as Yes. Would this be a major problem? Not for the long-term. I personally believe this would encourage people to do some research on the infrastructure of the CMS. It puts people at investigating where they did wrong and what they can do to improve/prevent it. Something that is seriously lacking in today Emulation Scene.

Answers have been posted up above. Closing report.
