### ISSUE TITLE
User groups & permissions → Roles

### ISSUE THREAD

**Issue by xabos** [FusionGen/FusionGEN#56]
**Describe the bug**
visual bug when  you go on the bottom and try to see the last 3-5 module provided role it's keeping open and close(I noticed that it does not occur every time may you have to refresh the page some times)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'admin control panel/User groups & permissions"
2. Click on 'roles'
3. Scroll down to 'bottom'
4. See module provide roles to keep opening and closing repeatedly.

**Expected behaviour**
Go to admin panel next section User groups & permissions next click on roles expect here to see roles module permissions all working perfectly keep going down everything again working correctly when I reach the bottom and try to see the last modules permissions they keep open and close repeatedly.

**Screenshots**
https://gyazo.com/ebfb0925c1c8b2f405a2657541d9e422

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10 pro]
 - Browser [e.g.vivaldi]
 - Version [
FusionGen master latest ver
PHP version | 7.1.30
CMS version | 1.0.1
]
**Additional context**

**Comment by mdjong1** [comment]
And what happens if you don't have your mouse hovered over the field? So you scroll down but have your mouse on the side?

**Comment by xabos** [comment]
I have the mouse on the side and I hovered over the field next and this occurs also this occurs and when I have it already hovered over the field and I go down

**Comment by OMGhixD-OG** [comment]
@xabos can you apply this change and confirm that its fixed?

**Comment by xabos** [comment]
https://github.com/FusionGen/FusionGEN/pull/57
fixed
