### ISSUE TITLE
AC core new password

### ISSUE THREAD

**Issue by mpfans** [FusionGen/FusionGEN#59]
**Describe the bug**
What would be the PHP algorithm to authenticate an AzerothCore account (make salt and verifier) after the sha_pass_hash field has been removed?
Before we used:
$sha_pass_hash = getPasswordHash($account_name, $password);
How does it work now? How to make salt and verifier to register a new account?

**To Reproduce**
1.open `password_recovery`
2.Enter your account 
3.look error

**Screenshots**
![image](https://user-images.githubusercontent.com/18187177/112662269-7557f480-8e92-11eb-806d-ba385f2fde41.png)

**Additional context**
https://github.com/azerothcore/azerothcore-wotlk/commit/485f7e76391a5bbf1af6b3219d27db721af38440

**Comment by Err0r1** [comment]
Use SRP6 branch?
https://github.com/FusionGen/FusionGEN/tree/master-srp6

**Comment by mpfans** [comment]
> Use SRP6 branch?
> https://github.com/FusionGen/FusionGEN/tree/master-srp6

Sorry, I didn't see this branch, I will test it

**Comment by mpfans** [comment]
> Use SRP6 branch?
> https://github.com/FusionGen/FusionGEN/tree/master-srp6
After installation, the following error is displayed:
![image](https://user-images.githubusercontent.com/18187177/112806682-a2322480-90a9-11eb-98eb-badc2f038872.png)

**Comment by mdjong1** [comment]
Replace your `emulator` in in your `realms` table within the database with `trinity_rbac_soap` or do a fresh reinstall

**Comment by mpfans** [comment]
> Replace your `emulator` in in your `realms` table within the database with `trinity_rbac_soap` or do a fresh reinstall

yes .. this is a reinstall.. Everything is brand new

I entered a realm information, but `relams` table didn't have any data

**Comment by mdjong1** [comment]
Did you do a fresh install _after_ you switched to SRP6? There is no reason it should be giving this error then.

**Comment by OMGhixD-OG** [comment]
Brief description:

User was not using the appropriate branch and user is now on a brand new issue. I suggest you take the tour towards our Discord Server and the Support Channel to resolve this remaining issue you are having.

https://discord.gg/anWGj79UNs
