### ISSUE TITLE
Trinitycore srp6 send item error

### ISSUE THREAD

**Issue by CraftedRO** [FusionGen/FusionGEN#61]
**Describe the bug**
Tested on 2534d25 srp6 branch
PHP version | 7.1.33
-- | --
CMS version | 1.0.1 
Emulator [Trinitycore 3.3.5](https://github.com/TrinityCore/TrinityCore/tree/3.3.5) | rev. 80f30d5ca94f

When I tried to send an item to character , the following errors result :
```
Something went wrong! An administrator has been noticed and will send your order as soon as possible.

Error:
Syntax: .send items #playername "#subject" "#text" itemid1[:count1] itemid2[:count2] ... itemidN[:countN] Send a mail to a player. Subject and mail text must be in "". If for itemid not provided related count values then expected 1, if count > max items in stack then items will be send in required amount stacks. All stacks amount in mail limited to 12.
```
**To Reproduce**
1. Go to 'http://localhost/store'
2. Click on 'send item'
3. See error

**Expected behavior**
The cms shoud send the requested item via soap to selected character.

**Screenshots**
![capturegen1](https://user-images.githubusercontent.com/24683355/113290268-12cf8000-92fa-11eb-8535-775538d8191a.JPG)

**Additional context**

**Comment by xabos** [comment]
Which way did you have make the item with console or item id???, looks like the wrong console wrong syntax

**Comment by CraftedRO** [comment]
item id

**Comment by xabos** [comment]
looks like emulator problem what emulator you use? update your issue with more details

**Comment by CraftedRO** [comment]
ok updated

**Comment by OMGhixD-OG** [comment]
The syntax is not ".sent items" its "send item"

We dont use "(DOTS)" in the console. And we dont use it in the editor through ACP either.

**Comment by CraftedRO** [comment]
Its default syntax from cms I only added the item ID in store so maybe you shoudn't close all the tickets without a clarification since you are the "maintainer" of this cms .

**Comment by OMGhixD-OG** [comment]
If its support related then there shouldn't be an dedicated issue report. We have a Discord Server for support. So yeah no this is suppose to be closed. 

Issue Trackers are solely for posting BUGS. They are not for tech-support.
