### ISSUE TITLE
Characters avatar does only show race images

### ISSUE THREAD

**Issue by CraftedRO** [FusionGen/FusionGEN#63]
**Describe the bug**

PHP version | 7.1.33
-- | --
CMS version | 1.0.1 

Im using srp6 branch ccad9b1

Characters avatars are wrong and only using race images check screenshoot.

**To Reproduce**
1. Go to 'http://localhost/profile/1'

**Expected behavior**
Characters avatar back then in fusioncms was showing the specific class/race image. like this :
![recovery2](https://user-images.githubusercontent.com/24683355/113504065-629e8900-953e-11eb-91cf-8b413c358d28.PNG)

**Screenshots**
![Capturezas](https://user-images.githubusercontent.com/24683355/113504083-70540e80-953e-11eb-8734-1045c7d86ec5.JPG)

**Additional context**

**Comment by OMGhixD-OG** [comment]
This is normal and the change was intentional.

**Comment by CraftedRO** [comment]
can I have a tip about where shoud I start the restoration for my own porposes ?
