### ISSUE TITLE
External account error

### ISSUE THREAD

**Issue by poryagholami1374** [FusionGen/FusionGEN#78]
Error Number: 1054

Unknown column 'sha_pass_hash' in 'field list'

SELECT id id, username username, sha_pass_hash password, email email, joindate joindate, last_ip last_ip, last_login last_login, expansion expansion FROM account WHERE username = 'test'

Filename: /home/trabes/domains/public_html/models/external_account_model.php

Line Number: 64

**Comment by OMGhixD-OG** [comment]
You should be using the Master-SRP6 branch not the master.

**Comment by OMGhixD-OG** [comment]
As this is not an cms error but rather a user error, this report will be closed. Information has been given on how to resolve it and or are available on other platforms from multiple sources.
