### ISSUE TITLE
New vMangos no longer supported !

### ISSUE THREAD

**Issue by Ayahuasca420** [FusionGen/FusionGEN#82]
**Describe the bug**
As the "sha_pass_hash" column was removed from the 'account' table in the last release of Elysium Core, FusionGen website is no longer able to correctly create an account or connect the user to his account.

**To Reproduce**
1. Simply use the latest version of Brotalnia's Elysium repack (v19 here : https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-emulator-servers/wow-emu-general-releases/613280-elysium-core-1-12-repack-including-mmaps-optional-vendors.html)
2. Try to create or connect a user on FusionGen using this repack's database
3. See error

**Expected behavior**
The website is intended to be able to create/manage user accounts.

**Additional context**
Initially, it should report a DB error. I tried adding back the "sha_pass_hash" column and the error is gone, but as the column is empty, the website is still unable to use it correctly.

Brotalnia's repack is made over vMangos : https://github.com/vmangos/core

**Comment by OMGhixD-OG** [comment]
So Elysium has SRP6?

If yes, use our SRP6 Branch.

**Comment by Ayahuasca420** [comment]
> So Elysium has SRP6?
> 
> If yes, use our SRP6 Branch.

It is possible, I see on my Trinity (using SRP6) columns like "salt", "verifier" and "session_key_auth", and on Elysium I'm finding "s", "v", and "sessionkey".
So, thanks to you for your answer (without it I don't know if I was ever going to find it out), I will try the SRP6 branch of FusionGen (like I use for my TrinityCore 3.3.5) later (I really need a big smoke right now). (:

**Comment by OMGhixD-OG** [comment]
That would indicate that Elysium has SRP6 :)

So yeah, please do use that branch. I'm unsure if theres an Emulator file for specifically Vmangos.. but if any, copy the TC_SOAP one and just duplicate and rename, modify to your likings and to ensure its onpar with the column requirements from Vmangos and that should be it.

**Comment by Ayahuasca420** [comment]
Okay, I just forked my WotLK website and edited it to match my Classic config & DB etc.. and edited the emulator file to match vMangos DB structure
When I try to log in with an account, I get this error : 

===========================================

Error Number: 1406

Data too long for column 's' at row 1

ALTER TABLE account MODIFY s binary(32) NULL

Filename: C:\TLK\Website\classic\system\database\DB_driver.php

Line Number: 328

===========================================

In the vMangos DB, the 's' column (salt) is a LONGTEXT type, not Binary(32). I'm stuck there (:

**Comment by Ayahuasca420** [comment]
Today I do not get the DB error, but instead the log-in  fails and the form shows a red cross next to the password like it is incorrect.

**Comment by Err0r1** [comment]
https://github.com/FusionGen/FusionGEN/issues/116
