### ISSUE TITLE
WoW Server Registiration Bug

### ISSUE THREAD

**Issue by nomad231** [FusionGen/FusionGEN#85]
Hi, i have found a wow server. When i reigster to web site i can register on site but i cant to server. I have take a error page. Error screenshot is attached. Please help.

My server version is v9.1 Shadowlands

my site: http://worldofwarcraftprime.com

![hata](https://user-images.githubusercontent.com/4716399/129393611-38140442-1da1-4007-b9cf-625a48b8ec71.png)

Thanks.

**Comment by CraftedRO** [comment]
are you sure that you are using fusiongen ?

**Comment by nomad231** [comment]
> are you sure that you are using fusiongen ?

Im using FusionCMS yes

**Comment by Err0r1** [comment]
FusionGEN or FusionCMS?

FusionCMS doesn't support shadowlands

**Comment by nomad231** [comment]
Im using fusioncms. So should i do? Anyway to transform fusioncms to fusiongen?

**Comment by Err0r1** [comment]
Never use FusionCMS
It's oudated and insecure.

**Comment by nomad231** [comment]
Ok thx. So how can i install fusionGen to my server. My Server is already active and i cant delete it.
