### ISSUE TITLE
404 not found error

### ISSUE THREAD

**Issue by nomad231** [FusionGen/FusionGEN#86]
Hi, i have installed the fusiongen but when i click register or another page link i take 404 not found error. I have copleted the insatallation and its forward me to the homepage. I need help. Thanks.

**Comment by nomad231** [comment]
I found new thing. If i write "127.0.0.1/index.php/register" to url i can go to register page but i cant go with "127.0.0.1/register" .  Can anyone help?

**Comment by OMGhixD-OG** [comment]
Please fill in the following format

Current issue encountering:

MySQL Version:
PHP Version:
Webhost or Xampp(ETC):
Latest FGEN Version (Yes/No):
Which branch (Master / SRP6):

**Comment by nomad231** [comment]
I have solved this problem. I added web.config file and its solved.
