### ISSUE TITLE
Unknown column 'sha_pass_hash' in 'field list' even with master-srp6

### ISSUE THREAD

**Issue by erictemponi** [FusionGen/FusionGEN#90]
I cloned FusionGEN with master-srp6 branch and installed it, but when I try to login or create an account, I get the error "Unknown column 'sha_pass_hash' in 'field list'" like I was using the master branch.

I'm using AzerothCore compiled yesterday without modifications.

Using this commit of FusionGEN on my pc (localhost): [e4bd60b](https://github.com/FusionGen/FusionGEN/commit/e4bd60bb85d6caf340c6519ad4e4bc810ea8b7b3)

To replicate this issue, just clone FusionGEN master-srp6 branch, install it and try to login.

I didn't modify anithing in the site.

PHP version: 7.1.33

**Comment by Ramys** [comment]
Tente modificar manualmente a tabela realm.
Já resolvi isso assim.

**Comment by erictemponi** [comment]
Modificar o que nela?

**Comment by Ramys** [comment]
Acabo de instalar https://github.com/FusionGen/FusionGEN/tree/master-srp6.
Não tive nenhum problema nesse momento com o erro "Unknown column 'sha_pass_hash' in 'field list'" like I was using the master branch.
Curto o seu trabalho desde a época do https://bg-games.forumeiro.com.
Será q vc n instalou a master?
Puxe diretamente da pasta DOWNLOAD.ZIP e depois atualize com o gitbash

**Comment by erictemponi** [comment]
Eu clonei só o master-srp6. Tem um errinho no emulador do AzerothCore. Resolvi o erro e tentei criar uma conta tanto com o emulador da Trinity quanto do Azeroth. Ambos retornam o erro mencionado no início.

Git Bash:
<img src="https://i.ibb.co/LphmWQV/fusiongen.png" />

Erro ao tentar criar conta:
<img src="https://i.ibb.co/DKsgvTb/fusiongen-error.png" />

**Comment by Ramys** [comment]
Dentro do Sqlyog, navicat ou qualquer q vc use, na aba que instalou o site , vá até realm, e adicione manualmente os dados da conta admin..
e mude o emulador lá para "azerothcore_soap"

**Comment by erictemponi** [comment]
Eu baixei o zip e agora funcionou, mas clonando direto não funciona, estranho.

**Comment by Ramys** [comment]
> Eu baixei o zip e agora funcionou, mas clonando direto não funciona, estranho.

sim , eu tive esse problema tb....só funcionou baixando o zipado.

**Comment by erictemponi** [comment]
Aqui ele puxou os dados de boa pra tabela realms.

Bom o problema está resolvido, mas acredito ser importante manter aberto aqui pro pessoal dar uma olhada no por que não funciona quando clona o repositório.

**Comment by Ramys** [comment]
Eu já avisei antes ao admin do projeto...fui ignorado !
enfim, vamo q vamo.

**Comment by erictemponi** [comment]
Vou fechar esta então. Vllw aí, meu chapa

**Comment by OMGhixD-OG** [comment]
What... i dont...

you know what, i'm not gonna ask.

glad you got it resolved! 
![image](https://user-images.githubusercontent.com/3145839/134083588-d0edb2ea-f08b-4aea-a161-533ffb5e9f55.png)

**Comment by Ramys** [comment]
> What... i dont...
> 
> you know what, i'm not gonna ask.
> 
> glad you got it resolved!
> ![image](https://user-images.githubusercontent.com/3145839/134083588-d0edb2ea-f08b-4aea-a161-533ffb5e9f55.png)

there is an error when pulling master-srp6 , master always comes..
and only via zip we can pull - master-srp6.

**Comment by OMGhixD-OG** [comment]
I didn't quite get that.

Please try again.
