### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by darkenam** [FusionGen/FusionGEN#94]
Hi @OMGhixD-OG

i use this version
https://github.com/FusionGen/FusionGen/tree/master-srp6

for last version azerothcore, but login and register have errors:

Error Number: 1054
Unknown column 'sha_pass_hash' in 'field list'

SELECT id id, username username, sha_pass_hash password, email email, joindate joindate, last_ip last_ip, last_login last_login, expansion expansion FROM account WHERE id = 0

Filename: /home/public_html/models/external_account_model.php
Line Number: 68

**Comment by Ramys** [comment]
Hi man....
Try this https://github.com/CraftedRO/FusionGen-SRP6

**Comment by darkenam** [comment]
thank you.

just in to user panel site have a errors:

A PHP Error was encountered
Severity: Warning
Message: count(): Parameter must be an array or an object that implements Countable
Filename: libraries/realms.php
Line Number: 328

**Comment by CraftedRO** [comment]
Use php 7.1 please :)

**Comment by darkenam** [comment]
oh yes,  thank you !

**Comment by mdjong1** [comment]
And do a better job on your issue description next time pleaseeeee, `BUG` is not extremely helpful

**Comment by Ramys** [comment]
Close this.

**Comment by OMGhixD-OG** [comment]
Azerothcore login issues should be fixed as of https://github.com/FusionGen/FusionGEN/commit/5c631de0bb7f998e0d228d6d3860f14b93b2b0f9

for the armory bug.

Please open a new issue report 

//Closing...
