### ISSUE TITLE
No Support for Shadowlands TrinityCore

### ISSUE THREAD

**Issue by grip244** [FusionGen/FusionGEN#97]
**Describe the bug**
There should be an option in the dropdown for shadowlands, it's the same commands, so yes you can use BFA (or edit it yourself), it would just be more convenient to have it added by default ^^

**Comment by OMGhixD-OG** [comment]
Master already has support for Shadowlands through WoD Emulator. We may or may not update this on the SRP6 Branch. Theres no point in updating it unless TCs official WoD Repo or an official WoD Org actually updates to it.

And most of our resources go into the SRP6 Repo. It is the most likely PW_Encryption method to remain used.

//Closed and noted down
